# Site settings
title: The Realm of Freyja
email: freyja@aesireanempire.com
description: "Realm of the random speakings of Freyjadono. Current Minecraft mod junkie, and long time enjoyer of all things computers."
baseurl: ""
url: "http://odininon.github.io"
git-username: odininon
twitter-username: mssodin28

# Build settings
markdown: kramdown
permalink: pretty
